### ISSUE TITLE
Anglais & PEP8

### ISSUE THREAD

**Issue by Otomatyk** [IrisyaAI/Irisya#1]
Hi ! 
Voici mes deux propositions : 
1. Tout le code est en anglais, pourquoi ce n’est pas le cas des messages d’`install.sh`?
2. Dans `app.py` il y’a pas mal de faute syntaxique qui ne respecte pas la PEP8, je conseil d’utiliser pylint pour régler tout ça

**Comment by VitriSnake** [comment]
Bonjjour,
Je voit que tu est français donc je te réponds en français.
Désolé d'avoir répondu si tard.
Pour l'anglais, tout le code sera en anglais et pour PEP8 je vais regarder ça.
Merci pour ton retours.

**Comment by Otomatyk** [comment]
Ok, mieux vaut tard que jamais :p

**Comment by VitriSnake** [comment]
J'ai traduit tout le ./install et ait ajouté un peu de PEP8.
Malgrès tout, une fois le code fait c'est un peu complexe mais je ferrais attention à l'avenir
